export const SET_BALANSE = 'BALANSE/SET_BALANSE'
export const FETCH_BALANSE = 'BALANSE/FETCH_BALANSE'

export const SPEND_BALANSE = 'BALANSE/SET_BALANSE'

export const PUSH_SPENDING = 'SPENDINGS/PUSH_SPENDING'
export const FETCH_SPENDINGS = 'SPENDINGS/FETCH_SPENDINGS'

export const PUSH_EARNING = 'EARNINGS/PUSH_SPENDING'
export const FETCH_EARNINGS = 'EARNINGS/FETCH_EARNINGS'

export const FETCH_TODAY_RECORDS = 'RECORDS/FETCH_TODAY_RECORDS'
export const PUSH_TODAY_RECORDS = 'RECORDS/PUSH_TODAY_RECORDS'

export const FETCH_ALL_RECORDS = 'RECORDS/FETCH_ALL_RECORDS'
export const PUSH_ALL_RECORDS = 'RECORDS/PUSH_ALL_RECORDS'

//in progress
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'