export const SET_BALANSE = 'BALANSE/SET_BALANSE'
export const FETCH_BALANSE = 'BALANSE/FETCH_BALANSE'

export const FETCH_SPENDINGS = 'SPENDINGS/FETCH_SPENDINGS'

export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'