export const SET_BALANSE = 'BALANSE/SET_BALANSE'
export const FETCH_BALANSE = 'BALANSE/FETCH_BALANSE'

export const SPEND_BALANSE = 'BALANSE/SET_BALANSE'

export const PUSH_SPENDING = 'SPENDINGS/PUSH_SPENDING'
export const FETCH_SPENDINGS = 'SPENDINGS/FETCH_SPENDINGS'



//in progress
export const SHOW_LOADER = 'APP/SHOW_LOADER'
export const HIDE_LOADER = 'APP/HIDE_LOADER'